import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction

abstract class GenerateVersionConstantsTask : DefaultTask() {
    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @get:Input
    abstract val pluginVersion: Property<String>

    @TaskAction
    fun generate() {
        val packageDir = outputDir.get().asFile.resolve("dev/namelessnanashi/namelessiplogger")
        packageDir.mkdirs()

        val constantsFile = packageDir.resolve("Constants.java")
        constantsFile.writeText(
            """
            package dev.namelessnanashi.namelessiplogger;

            public final class Constants {
            	public static final String VERSION = "${pluginVersion.get()}";

            	private Constants() {
            	}
            }
            """.trimIndent() + "\n"
        )
    }
}

plugins {
    java
    alias(libs.plugins.runvelocity)
    alias(libs.plugins.idea.ext)
}

val generatedVersionDir = layout.buildDirectory.dir("generated/sources/version/java/main")

val generateVersionConstants = tasks.register<GenerateVersionConstantsTask>("generateVersionConstants") {
    outputDir.set(generatedVersionDir)
    pluginVersion.set(version.toString())
}

repositories {
    maven("https://repo.papermc.io/repository/maven-public/")
    mavenCentral()
}

dependencies {
    compileOnly(libs.velocity)
    compileOnly(libs.paper.api)
    annotationProcessor(libs.velocity)
    implementation(libs.geoip2)
    implementation("org.apache.commons:commons-compress:1.27.1")
}

tasks {
    jar {
        duplicatesStrategy = DuplicatesStrategy.EXCLUDE
        from({
            configurations.runtimeClasspath.get()
                .filter { it.name.endsWith(".jar") }
                .map { zipTree(it) }
        })
    }

    compileJava {
        dependsOn(generateVersionConstants)
        options.encoding = Charsets.UTF_8.name()
        options.release.set(17)
    }
    clean {
        // Deletes the directory that is generated by the runVelocity plugin
        delete("run")
    }
    runVelocity {
        velocityVersion(libs.versions.velocity.get())
    }
}

sourceSets {
    main {
        java.srcDir(generatedVersionDir)
    }
}

java.toolchain.languageVersion.set(JavaLanguageVersion.of(17))
